prepend_path("PATH","/act/gcc-4.8.4/bin")
prepend_path("MANPATH","/act/gcc-4.8.4/share/man")
prepend_path("LD_LIBRARY_PATH","/act/gcc-4.8.4/lib64")
prepend_path("CPATH","/act/gcc-4.8.4/include")
set_alias("gcc48","/act/gcc-4.8.4/bin/gcc")
set_alias("g++48","/act/gcc-4.8.4/bin/g++")
set_alias("gfortran48","/act/gcc-4.8.4/bin/gfortran")
