whatis("Name: TransDecoder")
whatis("Version: 2.0.1")
whatis("Category: bioinformatics")
whatis("URL: http://transdecoder.github.io")
whatis("Description:  TransDecoder identifies candidate coding regions within transcript sequences, such as those generated by de novo RNA-Seq transcript assembly using Trinity, or constructed based on RNA-Seq alignments to the genome using Tophat and Cufflinks.")
prepend_path("PATH","/opt/transdecoder/2.0.1/gcc/util")
prepend_path("PATH","/opt/transdecoder/2.0.1/gcc/util/bin")
help([[
The TransDecoder  module file defines the following environment variables:
PATH for 
the location of the TransDecoder executibles.


Version 2.0.1
]])
