--
--Please place software website after text in the last 'whatis' (the description) separated by one new-line character.
--This way it will play nice with the script that populates the list of available software on Cowboy.
--
whatis("Name: MSTMAP")
whatis("Category: linkage, sequencing, mapping")
whatis("Description: MSTMap is a software tool that is capable of constructing genetic linkage maps efficiently and accurately.
http://alumni.cs.ucr.edu/~yonghui/mstmap.html")
--
--This part actually does stuff.
--
prepend_path("PATH","/opt/mstmap")
--
--Help description goes here:
--
help([[
MSTMap is a software tool that is capable of constructing genetic linkage maps efficiently and accurately. It can handle various mapping populations including BC1, DH, Hap, and RIL, among others. The tool builds the genetic linkage map by first constructing a Minimum Spanning Tree (MST), and hence the name MSTMap. The algorithm implemented in MSTMap is very efficient and can handle ultra-dense maps of up to 10,000~100,000 markers. According to our experimental studies, when the data quality is high, the accuracies of the maps produced by our tool are as good as those by the best tools available in the literature. However, when the data are noisy, the maps generated by our algorithm are significantly better.

Version:
--------
N/A

Website:
--------
http://alumni.cs.ucr.edu/~yonghui/mstmap.html
]])
